# Generated by Django 5.1.2 on 2024-11-03 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='citizen',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='users.citizen'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='surname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='passport_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
